volumes:
  postgres: ~
services:
  auth:
    build:
      dockerfile: Dockerfile
    environment:
      CONFIG_PATH: "./configs/dev.yml"
    ports:
      - "83:8080"
  postgres:
    ports:
      - "127.0.0.1:5434:5432"
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
