server:
  host: '0.0.0.0'
  port: '8000'

database:
  host: "postgres"
  port: 5432
  user: "pguser"
  password: "pguser"
  dbname: "db"
  timezone: "Europe/Moscow"

jwt:
  secret: 'key'
  ttl: 60 # в минутах
  refresh_ttl: 1440 # в минутах